### ISSUE TITLE
errors with Lucas's code

### ISSUE THREAD

**Issue by anastasia-morf** [ANU-RSES-Education/EMSC-4033-2022-assignment-Group3#50]
Hi @ltatnell, Here is a link to my tests for your code if you need to take a look. 
https://emsc4033.rses.underworldcloud.org/hub/user-redirect/lab/tree/EMSC-4033-2022-assignment-Group3/Lucas/tests/test_functions-Ana.py

None of my my_water_features tests worked but this is because you have used a different function, so that's ok. The rest all passed, except for  def test_my_point_data(): download_point_data() missing 1 required positional argument: 'min_magnitude'
I can't figure out why the error comes up but thought you should take a look. 

I will be waiting for your reply.

**Comment by ltatnell** [comment]
Yep, i've generalised the my_water_features function to be able to include any physical earth features, so i renamed it my_earth_features. The min_magnitude issue is due to not having a default min_magnitude in download_point_data, but I do have a default min_magnitude in my_point_data (which essentially does the same thing).

Thanks for bringing up these issues!

**Comment by anastasia-morf** [comment]
Ok that makes sense, thanks for explaining :) Code is looking really good.
